ALTER TYPE "Accent" ADD VALUE IF NOT EXISTS 'CANADIAN';
ALTER TYPE "Accent" ADD VALUE IF NOT EXISTS 'IRISH';
ALTER TYPE "Accent" ADD VALUE IF NOT EXISTS 'NEW_ZEALAND';
ALTER TYPE "Accent" ADD VALUE IF NOT EXISTS 'SOUTH_AFRICAN';
